spring:
  #redis连接配置
  redis:
    database: 0
    host: 47.106.8.7
    port: 6379
    password: 123456

    jedis:
      pool:
        max-active: 8
        max-wait: 2000m
        max-idle: 8
        min-idle: 0
    timeout: 2000m

  datasource:
    url: jdbc:mysql://localhost:3306/db_job?useUnicode=true&characterEncoding=UTF-8&serverTimezone=CTT
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat, wall,log4j2
  mvc:
    #映射静态资源
    static-path-pattern: /**

    #视图前后缀省略
    view:
      #prefix: /templates/views
      prefix: /WEB-INF/jsp/
      suffix: .jsp

  resources:
    static-locations: classpath:/**
    cache:
      period: 0
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  http:
    encoding:
      charset: utf-8
      force: true
      enabled: true

server:
  port: 8081

#关闭驼峰命名
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    #mybatis-plus配置控制台打印完整带参数SQL语句
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl



