spring:
  datasource:
    url: jdbc:mysql://139.196.98.86:3306/db_yy?useUnicode=true&characterEncoding=UTF-8&serverTimezone=CTT
    username: user
    password: user
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat, wall,log4j2
  mvc:
    #映射静态资源
    static-path-pattern: /**

    view:
      #prefix: /templates/views
      prefix: /WEB-INF/jsp/
      suffix: .jsp

  resources:
    static-locations: classpath:/**
    cache:
      period: 0
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  http:
    encoding:
      charset: utf-8
      force: true
      enabled: true

server:
  port: 8081
